### ISSUE TITLE
Exception bei fehlerhaften Bewegungsbefehlen

### ISSUE THREAD

**Issue by fantasya-pbem** [fantasya-pbem/host#2]
AW bricht ab:

null
Zeichenkette beschreibt keine gueltige Richtung.

java.lang.IllegalArgumentException: Zeichenkette beschreibt keine gueltige Richtung.
	at de.x8bit.Fantasya.Atlantis.Richtung.getRichtung(Richtung.java:106)
	at de.x8bit.Fantasya.Host.EVA.util.Reisen.Laufen(Reisen.java:255)
	at de.x8bit.Fantasya.Host.EVA.util.Reisen.Ausfuehren(Reisen.java:57)
	at de.x8bit.Fantasya.Host.EVA.NachUndRoute.DoAction(NachUndRoute.java:76)
	at de.x8bit.Fantasya.Host.EVA.EVABase.<init>(EVABase.java:104)
	at de.x8bit.Fantasya.Host.EVA.NachUndRoute.<init>(NachUndRoute.java:23)
	at de.x8bit.Fantasya.Host.EVA.EVABase.ZAT(EVABase.java:561)
	at de.x8bit.Fantasya.Host.Main.main(Main.java:303)

**Comment by fantasya-pbem** [comment]
Gefixt.
https://forum.fantasya-pbem.de/viewtopic.php?p=2002#p2002

Ursache war folgender Befehl:
ROUTE pause o so pause pause nw w PAUSE
