### ISSUE TITLE
Exception bei HANDEL Kaufe in Region ohne produziertes Luxusgut

### ISSUE THREAD

**Issue by fantasya-pbem** [fantasya-pbem/host#4]
In AW 408:

`java.lang.NullPointerException
	at de.x8bit.Fantasya.Host.EVA.Handeln.ExpandKaufen(Handeln.java:315)
	at de.x8bit.Fantasya.Host.EVA.Handeln.DoAction(Handeln.java:185)
	at de.x8bit.Fantasya.Host.EVA.EVABase.<init>(EVABase.java:114)
	at de.x8bit.Fantasya.Host.EVA.Handeln.<init>(Handeln.java:43)
	at de.x8bit.Fantasya.Host.EVA.EVABase.ZAT(EVABase.java:556)
	at de.x8bit.Fantasya.Host.Main.main(Main.java:303)
`

**Comment by fantasya-pbem** [comment]
Warum gibt es überhaupt Regionen ohne Produktion? Das ist doch sicher ein anderer Bug...

**Comment by fantasya-pbem** [comment]
Behoben.
